# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: tfsec

on:
  push:
    branches: [ prod, dev, staging ] # <-- Modified to include dev and staging
  pull_request:
    branches: [ prod ] # This is good as is for PRs targeting prod
  # schedule:
  #   - cron: '34 6 * * 5'

jobs:
  tfsec:
    name: Run tfsec sarif report
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
      - name: Clone repo
        uses: actions/checkout@v3 # <-- Changed to v3 as seen in lab examples

      - name: Run tfsec
        uses: tfsec/tfsec-sarif-action@9a83b5c3524f825c020e356335855741fd02745f # <-- Using the version/hash from lab example
        with:
          sarif_file: tfsec.sarif

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v1 # <-- Changed to v1 as seen in lab examples
        with:
          # Path to SARIF file relative to the root of the repository
          sarif_file: tfsec.sarif
